### ISSUE TITLE
height and width are not necessary to be power of two in NestedResidualUnet

### ISSUE THREAD

**Issue by quqixun** [lucidrains/x-unet#2]
AssertionError "height and width must be power of two" will be raised if shape of inputs are 384, 224, 192 etc.
It is possible to forward model using well designed ```nested_unet_depths``` and removing [#587](https://github.com/lucidrains/x-unet/blob/main/x_unet/x_unet.py#L587).

```python
import torch
from x_unet import XUnet

unet = XUnet(
    dim = 64,
    dim_mults = (1, 2, 4, 8),
    nested_unet_depths = (4, 3, 2, 1),
    consolidate_upsample_fmaps = True
)

img = torch.randn(1, 3, 384, 384)
out = unet(img)
print(out.size())
```

**Comment by lucidrains** [comment]
@quqixun yes, you are correct :pray: let me know if https://github.com/lucidrains/x-unet/commit/47571f2fcbc85afb0609ec361665a68696d72bca works!

**Comment by lucidrains** [comment]
@quqixun is the nested residual unet working well for your use-case?

**Comment by quqixun** [comment]
It works , thanks for updating.
