### ISSUE TITLE
Convnext 7-3-3 vs. 7-1-1

### ISSUE THREAD

**Issue by colllin** [lucidrains/x-unet#5]
Hi! In the original paper, it looks like convnext uses kernel sizes of 7, then 1, then 1.  But it looks like the implementation here is using 7-3-3.  Is this intentional?  Is 7-3-3 known to work better?

Thank you!

**Comment by lucidrains** [comment]
@colllin yea, it is intentional, mainly because i tried convnext in the context of ddpm and got better results with kernel size of 3. however, it is probably worth retrying with kernel size of 1 and with the global response normalization module they have in the updated architecture
